-- +goose Up
CREATE TABLE posts(
    id UUID PRIMARY KEY,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    title VARCHAR(100) NOT NULL,
    url VARCHAR(100) UNIQUE NOT NULL,
    description VARCHAR(300),
    published_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    feed_id UUID NOT NULL,
    CONSTRAINT feeds_fk FOREIGN KEY (feed_id) REFERENCES feeds (id) ON DELETE CASCADE
);

-- +goose Down
DROP TABLE posts;
